services:
  database:
    image: postgres
    container_name: database_atividade
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=atividade
      - POSTGRES_DB=atividade
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
